export const LOADING_SET_STATUS = 'LOADING_SET_STATUS'
export const LOADING_SET_INC_STATUS = 'LOADING_SET_INC_STATUS'
export const LOADING_FIRST_LOAD = 'LOADING_FIRST_LOAD'

export const PAGE_ADD_CONTENT = 'PAGE_ADD_CONTENT'
export const PAGE_ADD_MEDIA = 'PAGE_ADD_MEDIA'
export const PAGE_ADD_POST = 'PAGE_ADD_POST'
export const PAGE_ADD_FORM = 'PAGE_ADD_FORM'
export const PAGE_SEND_FORM = 'PAGE_SEND_FORM'
export const PAGE_STATUS_FORM = 'PAGE_STATUS_FORM'
export const PAGE_LIST_CONTENT = 'PAGE_LIST_CONTENT'
export const PAGE_TITLE_VALUE = 'PAGE_TITLE_VALUE'
export const PAGE_TITLE_BLEND = 'PAGE_TITLE_BLEND'
export const PAGE_TITLE_LINK = 'PAGE_TITLE_LINK'
export const PAGE_TITLE_ANIMATION = 'PAGE_TITLE_ANIMATION'
export const PAGE_PAGETITLE_VALUE = 'PAGE_PAGETITLE_VALUE'
export const PAGE_ADD_ARCHIVE_CATEGORY = 'PAGE_ADD_ARCHIVE_CATEGORY'

export const NAV_SET_OPEN = 'NAV_SET_OPEN'
export const NAV_GET_MAIN = 'NAV_GET_MAIN'
export const NAV_GET_MOBILE = 'NAV_GET_MOBILE'

export const SET_AUDIO_TO = 'SET_AUDIO_TO'

export const SET_SLIDERINDEX_TO = 'SET_SLIDERINDEX_TO'

export const SET_SWITCHER_TO = 'SET_SWITCHER_TO'

export const SET_SCROLL_TO = 'SET_SCROLL_TO'
export const ROUTING_ADD = 'ROUTING_ADD'

export const MODAL_SET_OPEN = 'MODAL_SET_OPEN'
export const MODAL_SET_IMAGE = 'MODAL_SET_IMAGE'

export const MEDIA_QUERIES_SET = 'MEDIA_QUERIES_SET'
export const MEDIA_QUERIES_SET_KEY = 'MEDIA_QUERIES_SET_KEY'

export const STRING_GET_ALL = 'STRING_GET_ALL'

export const POINTER_PROGRESS_TIME = 'POINTER_PROGRESS_TIME'
export const POINTER_HOVER = 'POINTER_HOVER'
export const POINTER_ICON = 'POINTER_ICON'
export const POINTER_LABEL = 'POINTER_LABEL'



// WEBPACK FOOTER //
// src/actions/types.js
