import { theme } from '../../style'

const style = () => ({
  root: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: 'var(--app-height)',
    zIndex: 11,
    transform: 'translateZ(0)',
  },
  wrap: {
    position: 'relative',
    top: 0,
    left: 0,
    width: '100vw',
    height: 'var(--app-height)',
    zIndex: 11,
    overflow: 'hidden',
    perspective: 200,
  },
  transition: {
    height: 'var(--app-height)',
    width: '100%',
    position: 'absolute',
    top: 0,
    left: '-100%',
    background: '#1c1a23',
    transform: 'scaleY(1.3) translateZ(0)',
  },
  pittogramma: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate3d(-50%, -50%, 100px) scale(0.8) rotationY(72deg)',
    zIndex: 10,
    opacity: 0,
    background: '#1c1a23',
    overflow: 'hidden',
    width: 60,
    height: 60,
    '& svg': {
      width: '100%',
      height: '100%',
      position: 'relative',
      zIndex: 1,
      overflow: 'hidden',
      display: 'block',
      fill: theme.colors[1],
      transformOrigin: 'center',
      transform: 'translateZ(0)',
    },
  },
  sterlingLogoWrap: {

  },
  firstTime: {
    position: 'fixed',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    zIndex: 1,
    padding: '30px 0 100px 0',
    '& $sterlingLogo': {
      display: 'block',
      width: '82px',
      height: '82px',
      margin: '0 auto',
      fill: '#fff',
    },
    '& $logo': {
      fill: '#fff',
      margin: '12px auto 7px',
      display: 'block',
      width: '83px',
      height: '14px',
    },
    '& .enterBtn': {
      textAlign: 'center',
      '& span': {
        margin: '0 auto',
        fontSize: 10,
        fontWeight: 600,
        letterSpacing: '0.2em',
        textTransform: 'uppercase',
        whiteSpace: 'nowrap',
        color: '#fff',
      },
      '& .cta': {
        display: 'block',
        margin: '7px auto',
        width: 40,
        height: 40,
      },
    },
  },
  sterlingLogo: {},
  logo: {},
  cookieLaw: {
    width: '100%',
    maxWidth: 410,
    padding: '0 10px',
    margin: '30px auto',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 1.3,
    fontFamily: '"Cutive Mono", monospace',
    color: 'rgba(255, 255, 255, .25)',
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    '& a': {
      color: 'rgba(255, 255, 255, .2)',
      textDecoration: 'underline',
    },
  },
  payoff: {
    width: '100%',
    maxWidth: 410,
    padding: '0 10px',
    margin: '30px auto 20px',
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 1.3,
    color: 'rgba(255, 255, 255, 1)',
  },
  enterBtn: {
    width: 120,
    margin: '0 auto',
    '& span': {
      cursor: 'pointer',
    },
  },
})

export default style
